#!/bin/bash
set -e

export PYTHONPATH="./env/lib/python3.10/site-packages:./:${PYTHONPATH}"
export PY_API_PREFIX="${PY_API_PREFIX:-/python-api}"

exec /var/lang/python310/bin/python3.10 -m uvicorn app:app --host 0.0.0.0 --port 9000
